project_name: cll-ibrutinib
project_description: cll-ibrutinib
username: arendeiro
email: arendeiro@cemm.oeaw.ac.at

metadata:
  output_dir: /scratch/lab_bock/shared/projects/cll-ibrutinib
  results_subdir: data
  submission_subdir: submission
  pipelines_dir: /home/arendeiro/workspace/open_pipelines
  sample_annotation: /scratch/lab_bock/shared/projects/cll-ibrutinib/metadata/annotation.csv
  merge_table: /scratch/lab_bock/shared/projects/cll-ibrutinib/metadata/merge_table.csv
  comparison_table: /scratch/lab_bock/shared/projects/cll-ibrutinib/metadata/comparison_table.csv

sample_attributes:
 - "sample_name"
 - "patient_id"
 - "timepoint_name"
 - "patient_gender"
 - "patient_age_at_collection"
 - "ighv_mutation_status"
 - "CD38_cells_percentage"
 - "leuko_count (10^3/uL)"
 - "% lymphocytes"
 - "purity (CD5+/CD19+)"
 - "%CD19/CD38"
 - "% CD3"
 - "% CD14"
 - "% B cells"
 - "% T cells"
 - "del11q"
 - "del13q"
 - "del17p"
 - "tri12"
 - "p53"
 - "time_since_treatment"
 - "treatment_response"

group_attributes:
 - "patient_id"
 - "timepoint_name"
 - "patient_gender"
 - "ighv_mutation_status"
 - "del11q"
 - "del13q"
 - "del17p"
 - "tri12"
 - "p53"
 - "time_since_treatment"
 - "treatment_response"

data_sources:
  bsf: /scratch/lab_bsf/samples/{flowcell}/{flowcell}_{lane}_samples/{flowcell}_{lane}#{BSF_name}.bam

genomes:
  human: hg19
  mouse: mm10

compute:
  submission_template: slurm_template.sub
  submission_command: sbatch

trackhubs:
  trackhub_dir: /data/groups/lab_bock/public_html/arendeiro/cll-ibrutinib/
  url: http://biomedical-sequencing.at/bocklab/arendeiro/cll-ibrutinib
